Console.ForegroundColor= ConsoleColor.DarkRed;
Console.WriteLine("Aleluia");
Console.WriteLine("Gabriela Rocha");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("Pai eu quero te amar");
Console.WriteLine("Tocar o teu coração");
Console.WriteLine("E me derramar aos teus pés");
Console.WriteLine("Mais perto quero estar Senhor");
Console.WriteLine("E te adorar com tudo o que eu sou");
Console.WriteLine("E te render glória e aleluia");
Console.WriteLine();
Console.ForegroundColor= ConsoleColor.DarkGreen;
Console.WriteLine("Aleluia aleluia");
Console.WriteLine("Aleluia aleluia");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("Quando lutas vierem me derrubar");
Console.WriteLine("Firmado em ti eu estarei");
Console.WriteLine("Pois tu és o meu refúgio, ó Deus");
Console.WriteLine("E não importa onde estiver");
Console.WriteLine("No vale ou no monte, adorarei");
Console.WriteLine("A ti eu canto glória e aleluia");
Console.WriteLine();
Console.ForegroundColor= ConsoleColor.DarkGreen;
Console.WriteLine("Aleluia aleluia");
Console.WriteLine("Aleluia aleluia");